### ISSUE TITLE
java error on  IDE: phpstorm 2024.2.0.1

### ISSUE THREAD

**Issue by morales2k** [nvlad/tinypng-optimizer#12]
phpstorm 2024.2.0.1  on linux (ubuntu 22.04 jammy)

latest available version of tinypng-optimizer (no available updates)

attempting to right click on anything sends out the alert on the notifications tray of IDE:

> com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.nvlad.tinypng.actions.Compress' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.nvlad.tinypng-optimizer]
> 	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
> 	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
> 	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
> 	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
> 	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
>

**Comment by adrianovcar** [comment]
+1

**Comment by wanglei1020** [comment]
+1

**Comment by artwc** [comment]
2024.2 以上版本用不了

**Comment by huhuang03** [comment]
https://github.com/huhuang03/tinypng-optimizer/releases/tag/v1.0.9
